name: Build  
  
on:  
  push:  
    branches:  
      - test
  pull_request:  
  workflow_dispatch:  
  
permissions:  
  contents: read  
  
jobs:  
  build:  
    runs-on: ubuntu-latest  
    steps:  
      - name: Checkout Repository  
        uses: actions/checkout@v4  
  
      - name: Grant Execute Permission for gradlew  
        run: chmod +x gradlew  
  
      - name: Setup Java  
        uses: actions/setup-java@v4  
        with:  
          java-version: '25'  
          distribution: 'zulu'  
  
      - name: Setup Gradle  
        uses: gradle/actions/setup-gradle@v4  
  
      - name: Build with Gradle  
        run: ./gradlew build --stacktrace  
  
      - name: Upload Build Artifacts  
        uses: actions/upload-artifact@v4  
        with:  
          name: mod-jars  
          path: build/libs/*.jar  
          if-no-files-found: error